### ISSUE TITLE
Render links in queries

### ISSUE THREAD

**Issue by wannli** [dvargas92495/roamjs-discourse-graph#10]
Thanks for a great plug-in. 

As nodes are identified by including links such as `[[EVD]]` in the title of a page, it would be tremendously useful if the queries could render these links in the same way as the links are rendered in a page.

**Comment by dvargas92495** [comment]
how do they currently differ?

**Comment by wannli** [comment]
Rendered link in link on page, with custom CSS:
![image](https://user-images.githubusercontent.com/57009124/163960458-dcc503ce-69bc-4b0b-a014-441a26bd43f9.jpeg)

Link in query:
![image](https://user-images.githubusercontent.com/57009124/163960667-bb02baf2-3d05-4563-945a-d5cf241eb9ac.jpeg)

**Comment by dvargas92495** [comment]
What is your custom css targeting? we're using similar CSS classes for the links in the table

**Comment by dvargas92495** [comment]
`data-link-title` are now added to the `a`  tags. so you'll just need to update your CSS to do `a[data-link-title....` along with the span declarations
