### ISSUE TITLE
discourse-graph possible regression?

### ISSUE THREAD

**Issue by umerazad** [dvargas92495/roamjs-discourse-graph#11]
@dvargas92495 / @joelchan  - First of all, thanks a ton for all your excellent work. Below is a bit of a regression report. 

I updated discourse-graph plugin to the latest bits and I see that the expanding the "Discourse Context" fails with the following unhandled exception:
 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/1691341/188298845-dc2e8bc6-30f9-46ce-aeb2-1d5538f0b0a1.png">

I did a bit of a version bisect and I suspect that the regression occurred between v08-04-21-49 (good) and v08-12-... (bad). I am able to reproduce it on a new graph with just a couple of nodes/relations too. 

Is this a known issue? Any workarounds?

P.S: I don't have query builder installed on my main graph.

**Comment by dvargas92495** [comment]
Thanks for catching! Should be fixed on the latest version
