### ISSUE TITLE
No default node list

### ISSUE THREAD

**Issue by pabloyler** [dvargas92495/roamjs-discourse-graph#12]
Hello, 
I recently installed the discourse-graph extension in Roam, and there no longer seems to be a default list of nodes (Claim, Evidence, Question, etc., so when you press the trigger button, there is an empty list of suggestions). Everything else seems to work fine though (the Informs, Supports, and Opposes default relations are there, but the Source and Destination blocks are undefined). I attached a screenshot.
![Screen Shot 2022-11-10 at 2 53 53 PM](https://user-images.githubusercontent.com/40147197/201193359-f5eac2c7-c8ac-428d-8ed7-f6e18cc72880.png)

**Comment by dvargas92495** [comment]
Should be fixed with the latest version!
