### ISSUE TITLE
First Load Error Querying Discourse Node

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-discourse-graph#13]
Version: v2022-11-07-16-53

When querying discourse nodes, on first load or reload, query comes up blank, or with errors.

I noticed this when developing a new dashboard, but when debugging I saw it on a previously implemented dashboard as well.
The previously implemented dashboard was in place a week ago, and I don't recall having the issue then, but I'm not 100% sure.
Just wondering if it's from Nov 7th changes.

**Video**

https://user-images.githubusercontent.com/3792666/201231326-1cab8e72-7bc9-4a68-b07b-76f5ec4c03d6.mp4

**Query**
```
[:find
  (pull ?node [:block/string :node/title :block/uid])
  (pull ?node [:block/uid])
:where
[(re-pattern "^\\[\\[EVD\\]\\] - (.*?)$") ?EVD--regex]
[?node :node/title ?node-Title]
[(re-find ?EVD--regex ?node-Title)]
]
```

**Chrome console log error**
![image](https://user-images.githubusercontent.com/3792666/201231271-c3e945da-8042-466a-b23d-38a5d1ef5668.png)

**Test Page**
https://roamresearch.com/#/app/DiscourseGraphAttributeTest/page/nNExmJRBa

**Comment by dvargas92495** [comment]
hm - on the latest version I see it working:
![Screen Shot 2022-11-15 at 9 38 12 AM](https://user-images.githubusercontent.com/7143571/201946829-88fef7ed-22d5-4e01-813a-d03a15d0e912.png)

Also going forward - we will be deprecating this repo so let's open all future issues on https://github.com/dvargas92495/roamjs-query-builder

**Comment by mdroidian** [comment]
Version: v2022-11-15-19-27

Still no good from me :(

https://user-images.githubusercontent.com/3792666/202030390-f3a420c7-a335-43f8-92b7-86467c662328.mp4

**Comment by dvargas92495** [comment]
Ah I understand what's happening now - the latest change should resolve
