### ISSUE TITLE
Cannot insert spaces into node texts in relation grammar diagrams

### ISSUE THREAD

**Issue by joelchan** [dvargas92495/roamjs-discourse-graph#3]
# Describe the bug
When editing notes in the relation grammar diagrams, it is not possible to include spaces in the node texts. The spacebar triggers a scrolldown on the page and does not insert a space.

# To Reproduce

1. Create new version of relation pattern
2. Create a node
3. Click to select node for editing text
4. Type some text and try to include a space with the spacebar

# Screenshots/Loom

https://www.loom.com/share/1e7c2fd2e5414cbcaaed200ecde26ec4

# System info

OS: Windows
Browser (n/a if using Desktop App): n/a
Roam setup (PWA, mobile, Desktop app): Desktop app
Version: 2021-08-16-17-09 (current)

**Comment by dvargas92495** [comment]
ah this was intentional - the in between nodes cant have names with spaces as that would break the datomic queries.

However, I forgot to account for the target node for "has title" requiring spaces. will see if I could discriminate between the two or just reallow it

**Comment by joelchan** [comment]
Ah that makes sense. We could also keep the constraint and require that the "has title" relation trigger words (that's what a user called them) are CamelCase (with no spaces). That might make it easier to integrate into OWL/RDF ontologies too.

**Comment by dvargas92495** [comment]
going to hold off on this bug for now, we could revisit in our meeting tomorrow

**Comment by dvargas92495** [comment]
What did we decide on this?
