### ISSUE TITLE
Link to PDF in RoamJS plugin gallery is 404

### ISSUE THREAD

**Issue by almereyda** [dvargas92495/roamjs-discourse-graph#4]
The link to the document http://joelchan.me/assets/pdf/Discourse_Graphs_for_Augmented_Knowledge_Synthesis_What_and_Why.pdf on https://roamjs.com/extensions/discourse-graph leads to a 404.

**Comment by joelchan** [comment]
updated pdf name to remove the extra underscore. link from roamjs.com works now.

**Comment by almereyda** [comment]
Thank you!
