### ISSUE TITLE
Is it possible to run a filter before actually loading all nodes to Discourse Graph Overview?

### ISSUE THREAD

**Issue by chengxu999** [dvargas92495/roamjs-discourse-graph#9]
I have more than 800 nodes using discourse graph, it takes about 10 mins to load when I open Discourse Graph Overview page. 

If I can run a filter before this page loads all my nodes, I can reduce the loading time and be more focused on a few ideas.

It seems to be a new feature request? I am not sure if I should post it here. Sorry.

**Comment by dvargas92495** [comment]
We've removed the overview and encourage use of the Playground instead
